name: 'Please Action'
description: 'An action for using the please build tool'
author: 'luke142367'
branding:
  color: green
  icon: triangle
inputs:
  args:  # id of input
    description: 'Arguments to plz command'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.args }}